services:
  # Servicio de producción
  el-macun-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: el-macun-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - el-macun-network
    restart: unless-stopped
    # Health check ya está definido en el Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  el-macun-network:
    driver: bridge

